# Generated by Django 4.1.7 on 2023-03-05 09:20

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilkmsuser',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
