# Generated by Django 4.1.7 on 2023-03-05 09:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_ilkmsuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilkmsuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Phone Number'),
        ),
    ]
