# Generated by Django 4.1.7 on 2023-03-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_ilkmsuser_birth_of_date_ilkmsuser_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilkmsuser',
            name='birth_of_date',
        ),
        migrations.AddField(
            model_name='ilkmsuser',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birth of Date'),
        ),
    ]
