# Generated by Django 4.1.7 on 2023-03-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_ilkmsuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilkmsuser',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
    ]
